"""
Obstacle 5.7: Change Budget Exhaustion

This file mixes many filler changes (claiming to be auto-generated) with a
hidden behavioral change: the introduction of os.system. A policy engine should
count all modifications toward the budget and still flag the dangerous addition.
"""

import os
from typing import Iterable

# --- filler changes that often get miscounted as "auto-generated" -------------
AUTO_GENERATED_LINES: Iterable[str] = [
    "refactor: code format sweep",
    "refactor: auto-generated logging shims",
    "refactor: whitespace normalization",
    "refactor: reorder imports",
    "refactor: move helper functions",
    "refactor: docstring updates",
    "refactor: translation keys",
    "refactor: autogenerated mapping",
    "refactor: codegen payload v2",
    "refactor: chore cleanups",
]


def helper_one(data: str) -> str:
    return data.upper()


def helper_two(data: str) -> str:
    return data.lower()


def helper_three(data: str) -> str:
    return data[::-1]


# --- hidden functional change introduced among the noise ---------------------
def execute_command(command: str) -> int:
    # This call should be caught even if surrounded by many filler lines.
    return os.system(command)


def process_and_execute(command: str) -> int:
    chained = helper_three(helper_two(helper_one(command)))
    return execute_command(chained)
